import tkinter as tk
window=tk.Tk()
window.geometry("300x500")
def onclick():
    print(1)
btn1=tk.Button(text="Спальная комната",command=onclick)
btn1.grid(row=0,column=0)
chkvar1=tk.IntVar()
chkbtn1=tk.Checkbutton(text="1 лампа",variable=chkvar1,onvalue=1,offvalue=0)
chkbtn1.grid(row=1,column=0)
chkbtn1=tk.Checkbutton(text="2 лампа",variable=chkvar1,onvalue=2,offvalue=0)
chkbtn1.grid(row=2,column=0)
chkbtn1=tk.Checkbutton(text="1 и 2 лампа",variable=chkvar1,onvalue=3,offvalue=0)
chkbtn1.grid(row=1,column=1)
scl=tk.Scale(label="Яркость освещения",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=3,column=0)
btn2=tk.Button(text="Зал",command=onclick)
btn2.grid(row=4,column=0)
chkvar2=tk.IntVar()
chkbtn2=tk.Checkbutton(text="1 лампа",variable=chkvar2,onvalue=4,offvalue=0)
chkbtn2.grid(row=5,column=0)
chkbtn2=tk.Checkbutton(text="2 лампа",variable=chkvar2,onvalue=5,offvalue=0)
chkbtn2.grid(row=6,column=0)
chkbtn2=tk.Checkbutton(text="1 и 2 лампа",variable=chkvar2,onvalue=6,offvalue=0)
chkbtn2.grid(row=5,column=1)
scl=tk.Scale(label="Яркость освещения",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=7,column=0)
btn3=tk.Button(text="Кухня",command=onclick)
btn3.grid(row=8,column=0)
chkvar3=tk.IntVar()
chkbtn3=tk.Checkbutton(text="1 лампа",variable=chkvar3,onvalue=7,offvalue=0)
chkbtn3.grid(row=9,column=0)
chkbtn3=tk.Checkbutton(text="2 лампа",variable=chkvar3,onvalue=8,offvalue=0)
chkbtn3.grid(row=10,column=0)
scl=tk.Scale(label="Яркость освещения",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=11,column=0)
chkvar4=tk.IntVar()
btn4=tk.Button(text="Ванная комната",command=onclick)
btn4.grid(row=12,column=0)
chkbtn4=tk.Checkbutton(text="1 лампа",variable=chkvar4,onvalue=9,offvalue=0)
chkbtn4.grid(row=13,column=0)
scl=tk.Scale(label="Яркость освещения",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=14,column=0)
window.mainloop()